### ISSUE TITLE
Can't generate html files "List was NULL"

### ISSUE THREAD

**Issue by 0ldude** [farfalleflickan/cmyflix#3]
Hi, i'm trying to set cmyflix up in a debian container in my homelab but even if it can correctly identify my TV show's episodes, after that it cannot create the static html pages from the dbTV.json even if it's full of correct entries.
I always get this error:
 [0.008467] createShowsHTML info: building HTML for TV shows...
 [0.008492] createShowsHTML error: list was NULL
P.S. I'm new to this but, am I supposed to already have an nginx instance running for this to work?

**Comment by farfalleflickan** [comment]
Hi!

Could you share your dbTV.json?
No, no nginx/webserver needed, that's only needed to serve the html files, but there is no interaction between cmyflix and anything else.

**Comment by 0ldude** [comment]
of course ,
here is the dbTV.json, i used jq for text formatting it but i get the same result with the one-line dbTV.json generated by cmyflix
https://privatebin.net/?1519546e4b0bc05e#82n2RKaEg8Mg5wwLF5WNRhnhTKmCJZfHifHSXMKBWsWq

**Comment by farfalleflickan** [comment]
Thank you, found the issue (and it was _REALLY_ stupid, my bad...). 
Let me know if it all works out for you so I can make a new release.

**Comment by 0ldude** [comment]
yeee, everything works. Don't worry stupid things happen. You are doing a good job :peace:
